name: Build and Test
on:
    push:
        branches-ignore:
            - master
    pull_request:
        branches-ignore:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run-script build:ci
    test-on-chrome:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Set Node Version
              uses: actions/setup-node@v2
              with:
                  node-version: 'v14.18.2'

            - name: Install dependencies
              run: npm --version

            - name: Install dependencies
              run: node --version

            - name: Install dependencies
              run: npm install

            - name: Install Chrome
              uses: browser-actions/setup-chrome@latest

            - name: Test with Chrome
              uses: GabrielBB/xvfb-action@v1
              with:
                  run: npm run-script test:chrome
    test-on-firefox:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  persist-credentials: false

            - name: Install dependencies
              run: npm install

            - name: Install Firefox
              uses: browser-actions/setup-firefox@latest

            - name: Test with Firefox
              uses: GabrielBB/xvfb-action@v1
              with:
                  run: npm run-script test
